set.seed(1024)
a = c(rnorm(100, 0), rnorm(50, 3), rnorm(30, 6))
b = c(rnorm(100, 8), rnorm(50, 4), rnorm(30, 0))
m = data.frame(a = a, b = b)
m = as.matrix(m)
d = dist(m)
fit = hclust(d)
g = cutree(fit, k = 3)
g = c(replicate(100,1), replicate(50,2), replicate(30,3))

tiff("cluster.tif", units ="in", width=6, height=6, res = 300)
plot(a[g == 1], b[g == 1], col = "red",  xlim = c(-3,10), ylim = c(-3, 15), xlab ="", ylab= "")
par(new = T)
plot(a[g == 2], b[g == 2], col = "green",  xlim = c(-3,10), ylim = c(-3, 15), xaxt = "n", yaxt = "n", xlab ="", ylab= "")
par(new = T)
plot(a[g == 3], b[g == 3], col = "blue",  xlim = c(-3,10), ylim = c(-3, 15), xaxt = "n", yaxt = "n", xlab ="", ylab= "")
dev.off()